# Generated by Django 5.0.6 on 2024-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='accountname',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='salary',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
