# Generated by Django 5.0.6 on 2024-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('firstName', models.FileField(default='', max_length=255, upload_to='')),
                ('lastName', models.CharField(default='', max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
