# Generated by Django 5.0.6 on 2024-09-01 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_application_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
