# Generated by Django 5.0.6 on 2024-09-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_employment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='profile_picture',
        ),
    ]
