# Generated by Django 5.0.6 on 2024-09-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_employment_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
