# Generated by Django 5.0.6 on 2024-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_files_financial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(default='null', max_length=255)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
