# Generated by Django 5.0.6 on 2024-09-16 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_topic_id_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='published_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
